project:
  type: website
  output-dir: docs

website:
  title: "Taxonomic Expert Workshop â€“ SB5"
  navbar:
    left:
      - text: "ğŸ  Inicio"
        file: 01_inicio.qmd
      - text: "ğŸ“… Agenda"
        file: agenda/index.qmd
      - text: "ğŸ‘¥ Participantes"
        file: participantes/01_participantes.qmd
      - text: "ğŸ“ LogÃ­stica"
        file: logistica/01_logistica.qmd
      - text: "ğŸ“‚ Recursos"
        file: recursos/materiales.qmd

  sidebar:
    style: docked
    contents:
      - section: "Agenda diaria"
        contents:
          - agenda/dia1.qmd
          - agenda/dia2.qmd
          - agenda/dia3.qmd
          - agenda/dia4.qmd
          - agenda/dia5.qmd
  page-footer:
    left: "Â© 2025 Isaac Brito-Morales"
    right: "Save the Blue 5"

format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    page-layout: article
    grid:
      sidebar-width: 280px
      body-width: 720px
    lang: es